name: Setup MySQL
inputs:
  mysql-version:
    description: The MySQL version to download (if necessary) and use
  database:
    description: Database to create
  user:
    description: User to create
runs:
  using: node24
  main: index.js
