name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            mysql-version: 8.0
          - os: ubuntu-18.04
            mysql-version: 8.0
          - os: ubuntu-18.04
            mysql-version: 5.7
          - os: macos-11.0
            mysql-version: 8.0
          - os: macos-11.0
            mysql-version: 5.7
          - os: macos-11.0
            mysql-version: 5.6
          - os: macos-10.15
            mysql-version: 8.0
          - os: macos-10.15
            mysql-version: 5.7
          - os: macos-10.15
            mysql-version: 5.6
          - os: windows-2019
            mysql-version: 8.0
          - os: windows-2019
            mysql-version: 5.7
          - os: windows-2019
            mysql-version: 5.6
          - os: windows-2016
            mysql-version: 8.0
          - os: windows-2016
            mysql-version: 5.7
          - os: windows-2016
            mysql-version: 5.6
    steps:
    - uses: actions/checkout@v2
    - uses: ./.
      with:
        mysql-version: ${{ matrix.mysql-version }}
        database: testdb
    - run: mysql --version
    - run: mysql -e 'SELECT VERSION()'
    - run: mysql -e 'SELECT CURRENT_USER()'
    - run: mysql -e 'SELECT DATABASE()'
    - run: mysql -e "SHOW VARIABLES LIKE 'socket'"
    - run: mysqladmin create testdb2
    - run: mysql -D testdb -e 'SELECT DATABASE()'
